import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import { ThemeProvider } from "@/components/ThemeProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ClashDisplay fonts
const clashDisplayRegular = localFont({
  src: "../components/fonts/ClashDisplay-Regular.woff2",
  variable: "--font-clash-display-regular",
  weight: "400",
});

const clashDisplaySemibold = localFont({
  src: "../components/fonts/ClashDisplay-Semibold.woff2",
  variable: "--font-clash-display-semibold",
  weight: "600",
});

const clashDisplayBold = localFont({
  src: "../components/fonts/ClashDisplay-Bold.woff2",
  variable: "--font-clash-display-bold",
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${clashDisplayRegular.variable} ${clashDisplaySemibold.variable} ${clashDisplayBold.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
